### ISSUE TITLE
Add Support in Network Connection Object For Defining Connections Between Hostnames

### ISSUE THREAD

**Issue by bworrell** [CybOXProject/python-cybox#119]
Update python-cybox to support https://github.com/CybOXProject/schemas/issues/133

**Comment by kkuehl** [comment]
Was this rejected?

**Comment by ikiril01** [comment]
@kkuehl, actually this was added for the CybOX v2.1 release and is supported in `python-cybox`. The Network Connection Object uses the Socket Address Object for its `Source_Socket_Address` and `Destination_Socket_Address` fields, which can use a hostname:

https://github.com/CybOXProject/python-cybox/blob/master/cybox/objects/socket_address_object.py#L22
