### ISSUE TITLE
Add support for crc32, SSDEEP, and IMPHASH in hashes

### ISSUE THREAD

**Issue by bworrell** [CybOXProject/python-cybox#165]
From the stix-discussion-list:

> The Hash object should be enhanced to support crc32 checksum, the SSDEEP and IMPHASH types of hashes. Looking at the commented code, it seems it is already an ongoing process.

**Comment by ateeqs** [comment]
Please add RIPEMD160 as a possible digest, in addition to CRC32.

**Comment by bworrell** [comment]
Thanks for the comment @ateeqs! The list of supported hash types is driven off of the [`HashNameVocab`](http://stixproject.github.io/data-model/1.1.1/cyboxVocabs/HashNameVocab-1.0/) CybOX default vocabulary schema type and enumeration, which currently does not include `CRC32` or `RIPEMD160`.

I would suggest adding an issue to the CybOX schemas repository [issue tracker](https://github.com/CybOXProject/Schemas/issues) for the inclusion of these hash types.

For the time being, it may be possible to use the method that @gtback proposed for the `CRC32` hash type, where the `xsi:type` attribute is explicitly set to `None`, thereby overriding the default `cyboxVocabs:HashNameVocab-1.0` value and allowing for schema-valid content.

```python
from cybox.common import Hash

h = Hash("37f332f68db77bd9d7edd4969571ad671cf9dd3b", "RIPEMD160")
h.type_.xsi_type = None
print h.to_xml()
```

**Comment by ateeqs** [comment]
Thanks, @bworrell. I'll put a ticket in the issue tracker for CybOX.
