### ISSUE TITLE
Whois Object is missing the Fax_Number parameter in the binding interface

### ISSUE THREAD

**Issue by CyberDaedalus00** [CybOXProject/python-cybox#227]
The __init__() operation of of the WhoIsRegistrantInfoType in the bindings interface is missing the Fax_Number and the Organization parameter in python-cybox 2.1.0.8 and 2.1.0.9.  Both parameters appears to be found in the __init__() of the WhoisContactType from which the WhoIsRegistrantInfoType inherits.

If one generates stubs from the current XML schema and trys to use the stubs against the python-cybox binding interface there will received the error 

super(WhoisRegistrantInfoTypeSub, self).__init__(contact_type, Contact_ID, Name, Email_Address, Phone_Number, Fax_Number, Address, Organization, Registrant_ID, )
TypeError: __init__() takes at most 8 arguments (10 given)

**Comment by ikiril01** [comment]
@CyberDaedalus00 thanks for reporting this! I can confirm that the current version of `python-cybox` exhibits this issue; we should be able to fix it for the next release.
