### ISSUE TITLE
Add __getitem__ and __setitem__ to Observables

### ISSUE THREAD

**Issue by bworrell** [CybOXProject/python-cybox#232]
Right now, `cybox.core.observable.Observables` implements `__len__()` and `__iter__()`. Trying to access an index directly via `my_observables_doc[0]` raises an error.

It might be helpful to implement `__getitem__` and `__setitem__`, or just make `Observables` a subclass of `EntityList` and get all the neato `MutableSequence` methods with it.

**Comment by gtback** [comment]
After playing around with this, I don't think subclassing `EntityList` is going to work without making further modifications to that class. Perhaps we could switch `Observables` over to using `TypedField`s, with `observables` having `multiple=True`, but this doesn't make it any easier to treat the `Observabels

**Comment by gtback** [comment]
Nevermind. The problems I was having were unrelated to this issue. Because `Observables` defines its own `(to|from)`_`(obj|dict)` functions to override the base `EntityList` ones, it still works as expected, while allowing the list-like interface.
