### ISSUE TITLE
README's link to generated_ds is dead

### ISSUE THREAD

**Issue by juandiana** [CybOXProject/python-cybox#248]
The [link provided](http://www.rexx.com/~dkuhlman/generateDS.html) in the README is dead.

Is [this](https://pypi.python.org/pypi/generateDS/2.15b) the correct package for generateDS?

**Comment by gtback** [comment]
Thanks, @juandiana. We can either use that link, or https://pythonhosted.org/generateDS/

We should make sure to update similar links in other projects as well.

**Comment by chisholm** [comment]
Fixed in ea68a33.
