### ISSUE TITLE
CIQ Address extension non mixboxified

### ISSUE THREAD

**Issue by bworrell** [CybOXProject/python-cybox#260]
I think the `cybox.extensions.location.ciq_address_3_0` module was left out of the mixboxification effort.

**Comment by gtback** [comment]
Well if we had **tests** for that extension... :wink: I'll get on it :smiley:

**Comment by gtback** [comment]
I can't find any XML examples that use this extension. Unless I find some (or example code), I'm tempted to just remove the extension from python-cybox.
