### ISSUE TITLE
Handle description on cybox Object class

### ISSUE THREAD

**Issue by rpiazza** [CybOXProject/python-cybox#300]
The code says it doesn't support this.  The slider needs a place to put STIX 2.0 properties that can't be represented

**Comment by gtback** [comment]
Could you put it on the Description of the Observable instead? If not, we could add it to Object as well (it shouldn't be too hard, since it subclasses mixbox.Entity.

**Comment by rpiazza** [comment]
That sounds like a good solution.

**Comment by gtback** [comment]
I'm going to leave this open, but remove it from the v2.1.0.15 milestone, since it should be pretty easy. For the slider, we can stick with the Observable description option.

**Comment by rpiazza** [comment]
Actually, it would be a lot better for the slider to able to attach missing properties to the Object, because when it is noticed missing the Observable isn't available without changing a lot of code.

**Comment by gtback** [comment]
Ok, I'll put it back in a milestone.
