### ISSUE TITLE
For some reason the Artifact typed fields don't include the type of the field...

### ISSUE THREAD

**Issue by rpiazza** [CybOXProject/python-cybox#304]

**Comment by gtback** [comment]
That's actually pretty standard for how we treat fields that end up being attributes in XML. Compare, for instance, the [FileObject](https://github.com/CybOXProject/python-cybox/blob/master/cybox/objects/file_object.py#L98-L99). They're almost always native Python types (str, bool, etc.), and the bindings typically cast these as appropriate.

I'm not saying it's the right way 😉 , but if we change this we should make sure to do it everywhere.

**Comment by rpiazza** [comment]
This isn't a bug - the problem was in the way it was called.
