### ISSUE TITLE
stix:ToolInformation should define type_ to be stix:AttackerToolTypeVocab

### ISSUE THREAD

**Issue by rpiazza** [CybOXProject/python-cybox#310]
Instead it inherits from cybox.common.ToolInformation, which wants to use the cybox-common:ToolType

see https://github.com/STIXProject/schemas/issues/39

**Comment by emmanvg** [comment]
I think we should just remove cybox-common:ToolType vocab. It should not be there correct?

     <xs:element name="Type" type="cyboxCommon:ControlledVocabularyStringType" minOccurs="0"
				maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>This field contains the type of the tool
						leveraged.</xs:documentation>
					<xs:documentation>This field is implemented through the xsi:type controlled
						vocabulary extension mechanism. No default vocabulary type has been defined
						for CybOX 2.0. Users may either define their own vocabulary using the type
						extension mechanism (by specifying a vocabulary name and/or reference using
						the vocab_name and vocab_reference attributes, respectively) or simply use
						this as a free string field. Additionally, locations where the
						ToolInformationType is used may define default vocabularies for this
						field.</xs:documentation>
				</xs:annotation>
			</xs:element>

**Comment by rpiazza** [comment]
I think the schema is correct - this is from the TTP schema

<xs:complexType name="ToolsType">
		<xs:sequence>
			<xs:element name="Tool" type="stixCommon:ToolInformationType" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>The Tool field specifies a single Tool leveraged by this TTP item.</xs:documentation>
					<xs:documentation>The Type field under this field is implemented through the xsi:type controlled vocabulary extension mechanism. The default vocabulary type is AttackerToolTypeVocab-1.0 in the http://stix.mitre.org/default_vocabularies-1 namespace. This type is defined in the stix_default_vocabularies.xsd file or at the URL http://stix.mitre.org/XMLSchema/default_vocabularies/1.2.0/stix_default_vocabularies.xsd.</xs:documentation>
					<xs:documentation>Users may also define their own vocabulary using the type extension mechanism, specify a vocabulary name and reference using the attributes, or simply use this as a string field.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

The issue is that the type_ in stix:ToolInformation class should override the type_ field from cybox.common.ToolInformation class with the TypedField defined as something like:

VocabField("Type", AttackerToolType, multiple=True)

**Comment by emmanvg** [comment]
I think this issue belongs to `STIXProject/python-stix`.

**Comment by gtback** [comment]
Yes, I think this is a python-stix issue. Are we missing something, @rpiazza ?

**Comment by emmanvg** [comment]
I can make this change, now my only concern is that if we state the type of vocab (in this case AttackerToolType) it will limit those values to the accepted values. They are case sensitive plus it will fail hard if anything else defined outside of this vocab is provided.

**Comment by emmanvg** [comment]
Considering that the tool is not breaking because of this, is this a priority to fix?

**Comment by rpiazza** [comment]
This fix is for the slider - see line 633 in stix2slider/convert_stix.py

**Comment by emmanvg** [comment]
The problem I currently have is that `cybox.common.tools.ToolInformation` has `type_` as a class variable. If I touch this, it will change all future instances of ToolInformation including `stix.common.tools.ToolsInformation` which inherits from cybox.

What I will do is override the type_ for `stix.common.tools.ToolsInformation` to the AttackerToolVocab since it is only used there.

**Comment by gtback** [comment]
Closed by #312
