### ISSUE TITLE
XSI_TYPE in vocabs not serialized due to logical error

### ISSUE THREAD

**Issue by emmanvg** [CybOXProject/python-cybox#313]
https://github.com/CybOXProject/python-cybox/blob/master/cybox/common/vocabs.py#L123 <br>Note the right-hand side of the `OR` expression will return `True` if an `XSI_TYPE` and `xsi_type` is set making `self.is_plain()` return `True` which is `False`...

**Comment by emmanvg** [comment]
It affects `to_dict()` because it makes use of it, but it can also affect the general code logic when used outside.

**Comment by emmanvg** [comment]
Actually, we can remove the `to_dict()` completely because TypedFields now takes case of None values

**Comment by gtback** [comment]
Can we add a test that demonstrates this? I remember why we made `is_plain()`, but I don't really understand the implications of this change.
