### ISSUE TITLE
IPv4 Multiple Addresses Helper Function Wrapping Observable in Observable

### ISSUE THREAD

**Issue by arcsector** [CybOXProject/python-cybox#322]
# Issue Details
IPv4 Multiple Addresses Helper Function (`create_ipv4_list_observables`) calls `create_ipv4_observable` function, which returns `Observable` type, but then attempts to wrap the `Observable` type in an `Observable` using the `Observable()` class constructor.

# Issue Fix
Don't do secondary wrapping, or don't return `Observable` type from `create_ipv4_observable` function.

# Issue Location
Issue is in the helper functions [here](https://github.com/CybOXProject/python-cybox/blob/master/cybox/helper.py#L32).

**Comment by emmanvg** [comment]
Closed by #323
